package com.alex.demo.mybatis.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_no
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    private String deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_name
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_no
     *
     * @return the value of departments.dept_no
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_no
     *
     * @param deptNo the value for departments.dept_no
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_name
     *
     * @return the value of departments.dept_name
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_name
     *
     * @param deptName the value for departments.dept_name
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}