package com.alex.demo.mybatis.model;

import java.util.Date;

public class DeptEmp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.emp_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    private Integer empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.dept_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    private String deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.from_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    private Date fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.to_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    private Date toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.emp_no
     *
     * @return the value of dept_emp.emp_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.emp_no
     *
     * @param empNo the value for dept_emp.emp_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.dept_no
     *
     * @return the value of dept_emp.dept_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.dept_no
     *
     * @param deptNo the value for dept_emp.dept_no
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.from_date
     *
     * @return the value of dept_emp.from_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.from_date
     *
     * @param fromDate the value for dept_emp.from_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.to_date
     *
     * @return the value of dept_emp.to_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.to_date
     *
     * @param toDate the value for dept_emp.to_date
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
}