package com.alex.demo.mybatis.mapper;

import com.alex.demo.mybatis.model.DeptEmp;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int deleteByPrimaryKey(@Param("empNo") Integer empNo, @Param("deptNo") String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int insert(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    DeptEmp selectByPrimaryKey(@Param("empNo") Integer empNo, @Param("deptNo") String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    List<DeptEmp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int updateByPrimaryKey(DeptEmp record);
}