package com.alex.demo.mybatis.mapper;

import com.alex.demo.mybatis.model.DeptManager;
import java.util.List;

public interface DeptManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    int insert(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    List<DeptManager> selectAll();
}