package com.alex.demo.mybatis.mapper;

import com.alex.demo.mybatis.model.Salaries;
import java.util.List;

public interface SalariesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    int insert(Salaries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    List<Salaries> selectAll();
}