package com.alex.demo.mybatis.mapper;

import com.alex.demo.mybatis.model.Titles;
import java.util.List;

public interface TitlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    int insert(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue May 28 14:24:28 CST 2019
     */
    List<Titles> selectAll();
}