package com.alex.demo.mybatis.mapper;

import com.alex.demo.mybatis.model.Titles;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TitlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int deleteByPrimaryKey(@Param("empNo") Integer empNo, @Param("title") String title, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int insert(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    Titles selectByPrimaryKey(@Param("empNo") Integer empNo, @Param("title") String title, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    List<Titles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated Tue Sep 24 10:04:15 CST 2019
     */
    int updateByPrimaryKey(Titles record);
}